version: "3.8"
services:
    web:
        build:
            context: . 
            dockerfile: Dockerfile.mlflow
        image: saldern/mlflow-server:latest
        container_name: mlflow-server
        networks: 
            - frontend
        expose: 
            - "5000"
        volumes:
            - "./mlruns:/mlflow/mlruns:rw"

    nginx:
        build: ./nginx
        image: saldern/mlflow-nginx:latest
        container_name: mlflow-nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - web


networks: 
  frontend: