# !! Conda is not activated in pipeline
# !! Miniconda with Python 2 only

FROM continuumio/miniconda
LABEL version="0.0.3"
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
WORKDIR /app
COPY . .
CMD [ "python", "pipeline.py", "-d", "data", "-m", "models", "-o", "output" ]
