FROM python:3.8.6-slim

ARG MLFLOW_VERSION=1.12.1
RUN pip3 install --no-cache-dir mlflow==${MLFLOW_VERSION}

ARG USER_ID=1000
RUN useradd -M --no-log-init --system  --uid ${USER_ID} mlflow

USER mlflow
WORKDIR /mlflow

CMD ["mlflow", "server", "--host", "0.0.0.0", "--default-artifact-root", "ftp://mlflow:mlflow@localhost"]
