stages:
  filter:
    cmd: python scripts/filter.py data/data.csv
    deps:
    - data/data.csv
    - scripts/filter.py
    params:
    - filter.date
    outs:
    - data/filtered
  split:
    cmd: python scripts/split.py data/filtered/filtered.csv
    deps:
    - data/filtered/filtered.csv
    - scripts/split.py
    outs:
    - data/splitted
  feature_extraction:
    cmd: python scripts/featurization.py data/splitted/report.csv
    deps:
    - data/splitted/report.csv
    - scripts/featurization.py
    outs:
    - data/features
  train_test_split:
    cmd: python scripts/train_test_split.py data/features/features.pkl data/splitted/parsed.csv
    deps:
    - data/features/features.pkl
    - data/splitted/parsed.csv
    - scripts/train_test_split.py
    outs:
    - data/test
    - data/train
  train:
    cmd: python scripts/train.py data/train/train_pairs.pkl models/LogRegElasticNet.pkl
    deps:
    - data/train/train_pairs.pkl
    - scripts/train.py
    outs:
    - models
  evaluate:
    cmd: python scripts/evaluate.py models/LogRegElasticNet.pkl data/test/test_pairs.pkl
      results/logreg_scores.json
    deps:
    - data/test/test_pairs.pkl
    - models/LogRegElasticNet.pkl
    - scripts/evaluate.py
    metrics:
    - results/logreg_scores.json:
        cache: false
