# !! Conda is not activated in pipeline
# !! Miniconda with Python 2 only
# ! Don't use this file. For experimenting only.

FROM continuumio/miniconda:4.7.12
LABEL version="0.0.3"
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
WORKDIR /app
COPY . .
CMD [ "python", "scripts/inference.py", "-d", "data", "-m", "models", "-o", "output" ]
