# Unfortunately broken on Alpine image (python:3-alpine)

# Bare Python
FROM python:3.8.4
LABEL version="0.0.2"
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
COPY . .
CMD [ "python", "scripts/inference.py", "-d", "data", "-m", "models", "-o", "output" ]
